name: publish
on: [push]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build the image
    run: |
      docker build . --tag ghcr.io/CedricBaaklini/Docker-Demo
      docker run ghcr.io/deselikem/CedricBaaklini/Docker-Demo
      docker push ghcr.io/deselikem/CedricBaaklini/Docker-Demo
